### ISSUE TITLE
Residue Count Mismatch between Input File and Logged Output

### ISSUE THREAD

**Issue by poinco-gogo** [EPISOLrelease/EPISOL#1]
Dear developers,

Thank you for making this project open source.
As mentioned in the title, there is a discrepancy between the residue count in the input file and the residue count displayed in the log. Specifically, my protein consists of 439 residues, but the log shows a count of 406 residues.

After examining the source code (main-sub.cpp, main_print_solute_list()), I suspect that there might be an issue with how EPISOL counts residues. For instance, when there are consecutive residues with the same residue name, such as ALA100 and ALA101, EPISOL seems to consider them as a single residue. In fact, when I wrote a Python code using a similar counting approach, my protein was recognized as having 406 residues.
Here is the source code:
```
with open("my_protein.pdb", 'r') as f:
    nres = 0
    prev = "foo"
    for line in f:
        if line.startswith("ATOM"):
            resname = line[17:20]
            if resname != prev:
                nres += 1
                prev = resname
    print(nres)
```

My concern is whether this discrepancy would affect the calculation results. Even if the residue count is incorrect, as long as the structure and parameters are properly loaded, I believe the results would still be accurate. However, please correct me if I have overlooked something. I apologize for any misunderstanding.

Sincerely,

**Comment by seechin** [comment]
Hi, Koichi,

Thank you for letting us know the issue of EPISOL.

The old kernel of EPISOL did have an issue of incorrect counting of residue numbers. This number of residues was only used to be displayed in log files, and will not affect any of the following 3DRISM calculations.

Now this issue has been resolved in EPISOL 1.2 (with kernel 1.2.3). Kernel v1.2.3 of EPISOL will count the number of residues according to the residue number in TOP files. This bug fix has been listed in src/kernel/release/UPDATE.md (after installation of the kernel).

But currently we only tested this issue for GROMACS TOP files. If you find this issue with PRMTOP files, please feel free to contact us.

Regards,
Siqin

-
Siqin Cao, PhD
Scientist
Department of Chemistry
University of Wisconsin-Madison
E-mail: ***@***.***
Web: https://huang.chem.wisc.edu

On May 21, 2023, at 5:34 PM, Koichi TAMURA ***@***.***> wrote:



Dear developers,

Thank you for making this project open source.
As mentioned in the title, there is a discrepancy between the residue count in the input file and the residue count displayed in the log. Specifically, my protein consists of 439 residues, but the log shows a count of 406 residues.

After examining the source code (main-sub.cpp, main_print_solute_list()), I suspect that there might be an issue with how EPISOL counts residues. For instance, when there are consecutive residues with the same residue name, such as ALA100 and ALA101, EPISOL seems to consider them as a single residue. In fact, when I wrote a Python code using a similar counting approach, my protein was recognized as having 406 residues.
Here is the source code:

with open("my_protein.pdb", 'r') as f:
    nres = 0
    prev = "foo"
    for line in f:
        if line.startswith("ATOM"):
            resname = line[17:20]
            if resname != prev:
                nres += 1
                prev = resname
    print(nres)


My concern is whether this discrepancy would affect the calculation results. Even if the residue count is incorrect, as long as the structure and parameters are properly loaded, I believe the results would still be accurate. However, please correct me if I have overlooked something. I apologize for any misunderstanding.

Sincerely,

**Comment by poinco-gogo** [comment]
Dear developers,

Thank you for promptly fixing the residue numbering issue in EPISOL. I have tested the latest version and confirmed that the issue has been resolved. The residue numbers are now accurate!

I appreciate your quick response and commitment to maintaining the quality of the project.

Best regards,
Koichi

**Comment by poinco-gogo** [comment]
one more thing to add. I used .prmtop file for the calculation, and I must mention that the residue numbers were correctly displayed.
